import {createGridModel} from './grid-model.js';
import {createRenderer} from './renderer.js';
import {createContactState} from './contact-state.js';
import {frameFor,clamp,surfacePoint,ridgeAt} from './surface.js';
const $=s=>document.querySelector(s),canvas=$('#membrane'),stage=$('#stage'),journey=$('#journey'),status=$('#status');
const params=new URLSearchParams(location.search),contact=createContactState(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const settings={grid:params.get('grid')!=='off',quality:params.get('quality')==='balanced'?'balanced':'full'};
if(params.get('clean')==='1')document.body.classList.add('clean');
let renderer=null,grid=null,frame=null,gridKey='',device='',generation=0,loader=null,raf=0,lastTime=0,destroyed=false,suspended=false,inView=true,active=null,gestureBlocked=false,startXY=null,progress=0,transition=0,passiveReveal=0,replayName=null,replayStart=0,transferHit=[.42,.55];
const pointers=new Set(),removers=[],timers=new Set();
const stats={draws:0,frames:0,solverFrames:0,solverMs:0,maxSolverMs:0,drawMs:0,maxDrawMs:0,releases:0,lastRelease:'rest',restoreCount:0,error:null,frameIntervals:[],solverTimes:[],drawingTimes:[],samples:[],inputs:[],reactions:[],rafLog:[]};
const bounded=(list,value)=>{list.push(value);if(list.length>5000)list.splice(0,list.length-5000);};
function on(target,event,fn,options){target.addEventListener(event,fn,options);removers.push(()=>target.removeEventListener(event,fn,options));}
function later(fn,ms){const id=setTimeout(()=>{timers.delete(id);if(!destroyed&&!suspended)fn();},ms);timers.add(id);return id;}
function clearTimers(){for(const id of timers)clearTimeout(id);timers.clear();replayName=null;}
function live(){return!destroyed&&!suspended&&!document.hidden&&inView;}
function requestDraw(){if(!raf&&live()&&renderer){raf=requestAnimationFrame(tick);bounded(stats.rafLog,{time:performance.now(),event:'request'});}}
function stopRAF(reason){if(raf)cancelAnimationFrame(raf);raf=0;lastTime=0;bounded(stats.rafLog,{time:performance.now(),event:'stop',reason});}
function pose(){const c=contact.snapshot();return{contact:c.contact,reveal:Math.max(c.reveal,passiveReveal),hit:transition>0?transferHit:c.reveal>0||c.down?c.hit:[.42,.55],transition,grid:settings.grid&&!reduced.matches};}
let pendingReaction=null,expectedScrollY=null;
function draw(){if(!renderer||!frame||!live())return false;const t=performance.now(),p=pose();if(!renderer.draw(frame,p,grid))return false;const end=performance.now(),ms=end-t;stats.draws++;stats.drawMs+=ms;stats.maxDrawMs=Math.max(stats.maxDrawMs,ms);bounded(stats.drawingTimes,ms);bounded(stats.samples,{time:end,contact:p.contact,reveal:p.reveal,hit:[...p.hit],transition:p.transition,grid:p.grid,gridActive:Boolean(grid?.active),gridRevision:grid?.revision});stage.dataset.contact=p.contact.toFixed(4);stage.dataset.reveal=p.reveal.toFixed(4);
 if(pendingReaction&&(p.contact>0||p.reveal>0)){bounded(stats.reactions,{...pendingReaction,firstDraw:end,softwareMs:end-pendingReaction.receivedAt,eventToDrawMs:end-pendingReaction.eventTime,measurement:'CPU draw submission, not physical display'});pendingReaction=null;}return true;}
function tick(time){raf=0;if(!live()||!renderer){lastTime=0;return;}const interval=lastTime?time-lastTime:null,dt=interval===null?1/60:Math.min(interval/1000,1/30);if(interval!==null){stats.frames++;bounded(stats.frameIntervals,interval);}lastTime=time;
 if(replayName==='drag'){const t=clamp((time-replayStart)/900);contact.move([.32+.32*t,.55]);}
 const c=contact.update(time,dt);
 if(settings.grid&&!reduced.matches&&grid&&(c.contact>0||grid.active)){const t=performance.now();try{grid.step(dt,c.hit,c.contact);}catch(e){stats.error=e.message;settings.grid=false;$('#grid-toggle').checked=false;grid.reset();status.textContent='面の計算を停止しました。固定した面で操作と縦進行を続けられます。';}const ms=performance.now()-t;stats.solverFrames++;stats.solverMs+=ms;stats.maxSolverMs=Math.max(stats.maxSolverMs,ms);bounded(stats.solverTimes,ms);}
 draw();if(c.active||(settings.grid&&!reduced.matches&&grid?.active))requestDraw();else{lastTime=0;bounded(stats.rafLog,{time,event:'idle'});}}
function release(reason='release',normal=false){const now=performance.now();const previous=active;active=null;startXY=null;contact.release(reason,now,normal);clearTimers();stats.releases++;stats.lastRelease=reason;bounded(stats.inputs,{time:now,type:'release',reason,normal});if(typeof previous==='number'&&canvas.hasPointerCapture(previous))canvas.releasePointerCapture(previous);requestDraw();}
function begin(hit,event=null,source='replay'){if(!renderer||!live()||progress>.45)return false;clearTimers();const now=performance.now();contact.begin(hit,now);pendingReaction={receivedAt:now,eventTime:event?.timeStamp||now,source,hit:[...hit]};bounded(stats.inputs,{time:now,eventTime:pendingReaction.eventTime,type:'begin',source,hit:[...hit]});draw();requestDraw();return true;}
function scrollProgress(){const r=journey.getBoundingClientRect(),span=Math.max(1,journey.offsetHeight-stage.offsetHeight),next=clamp(-r.top/span);if(progress<=.45&&next>.45)transferHit=[...pose().hit];progress=next;passiveReveal=clamp((progress-.12)/.33);transition=clamp((progress-.45)/.55);stage.style.setProperty('--transition',transition.toFixed(5));stage.style.setProperty('--s1-title',clamp((transition-.7)/.3).toFixed(5));stage.dataset.progress=progress.toFixed(5);if(progress>.45&&(active!==null||contact.snapshot().down||replayName))release('transition');draw();requestDraw();}
function updateImages(next){$('#fallback-rest').src=`assets/rest-${next}.webp`;$('#fallback-s1').src=`assets/s1-${next}.webp`;$('#reference').src=`assets/s0-${next}.webp`;}
function size(){const r=stage.getBoundingClientRect();if(r.width<1||r.height<1)return;frame=frameFor(r.width,r.height);const next=frame.portrait?'sp':'pc',key=`${r.width},${r.height}`;if(key!==gridKey){grid?.dispose();grid=createGridModel(frame,r.width,r.height);gridKey=key;if(active!==null)release('resize');}
 const full=settings.quality==='full',dpr=Math.min(devicePixelRatio||1,full?(frame.portrait?1.25:1.5):(frame.portrait?1:1.25)),maxSide=full?(frame.portrait?1400:2400):(frame.portrait?1100:1800),limit=Math.min(1,maxSide/Math.max(r.width*dpr,r.height*dpr));canvas.width=Math.max(1,Math.round(r.width*dpr*limit));canvas.height=Math.max(1,Math.round(r.height*dpr*limit));stage.dataset.layout=next;stage.dataset.quality=settings.quality;
 if(next!==device){device=next;updateImages(next);if(!suspended&&!destroyed)ready();}else{draw();requestDraw();}scrollProgress();}
async function ready(){if(destroyed||suspended)return;const token=++generation;loader?.abort();loader=new AbortController();renderer?.dispose();renderer=null;stopRAF('rebuild');stage.dataset.renderer='loading';try{if(params.has('fallback'))throw Error('Requested static fallback');const next=await createRenderer(canvas,device,settings.quality,{signal:loader.signal});if(token!==generation||destroyed||suspended){next.dispose();return;}renderer=next;stage.dataset.renderer='webgl2';stats.error=null;canvas.tabIndex=0;canvas.setAttribute('aria-label','触れる、または横に動かすと奥の景色が見える黒い面');status.textContent=reduced.matches?'動きを低減。固定した面で奥の像が応じます。':'触れる・横に動かす / 縦に進む';draw();requestDraw();}catch(error){if(token!==generation||destroyed||suspended||error.name==='AbortError')return;renderer=null;stage.dataset.renderer='static';stats.error=error.message;canvas.tabIndex=-1;canvas.setAttribute('aria-label','静止画を表示中。面の操作はできません。縦スクロールで進めます。');status.textContent='描画を利用できないため静止画を表示中。面の操作はできません。縦スクロールで進めます。';release('fallback');stopRAF('fallback');}}
function hitFromEvent(e){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x<8||x>r.width-8||y<8||y>r.height-8)return null;for(const node of document.querySelectorAll('.scene-title,.scene-title-s1,.caption')){if(Number(getComputedStyle(node).opacity)===0||getComputedStyle(node).display==='none')continue;const t=node.getBoundingClientRect();if(e.clientX>=t.left-8&&e.clientX<=t.right+8&&e.clientY>=t.top-8&&e.clientY<=t.bottom+8)return null;}return[x/r.width,(y/r.height-.5)*frame.scaleY+.5];}
on(window,'pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1){gestureBlocked=true;release('multitouch');}},{passive:true,capture:true});
on(canvas,'pointerdown',e=>{if(!renderer||e.button!==0||gestureBlocked||pointers.size>1||progress>.45)return;const hit=hitFromEvent(e);if(!hit)return;if(active!==null)release('new contact');active=e.pointerId;startXY=[e.clientX,e.clientY];if(e.pointerType==='mouse')canvas.setPointerCapture(e.pointerId);begin(hit,e,'pointer');},{passive:true});
on(window,'pointermove',e=>{if(active!==e.pointerId||gestureBlocked)return;if(e.pointerType==='touch'&&startXY&&Math.abs(e.clientY-startXY[1])>12){release('vertical gesture');return;}const hit=hitFromEvent(e);if(!hit){release('outside');return;}contact.move(hit);bounded(stats.inputs,{time:performance.now(),type:'move',hit:[...hit]});draw();requestDraw();},{passive:true});
function endPointer(e){pointers.delete(e.pointerId);if(active===e.pointerId)release(e.type,e.type==='pointerup');if(pointers.size===0)gestureBlocked=false;}
on(window,'pointerup',endPointer,{passive:true});on(window,'pointercancel',endPointer,{passive:true});on(canvas,'lostpointercapture',()=>{if(active!==null)release('lostpointercapture');},{passive:true});
on(window,'pointerout',e=>{if(e.relatedTarget===null&&active!==null)release('window leave');},{passive:true});
on(window,'blur',()=>{pointers.clear();gestureBlocked=false;release('blur');stopRAF('blur');});
on(window,'focus',()=>requestDraw());
on(window,'scroll',()=>{const expected=expectedScrollY!==null&&Math.abs(window.scrollY-expectedScrollY)<1;expectedScrollY=null;if(!expected&&(active!==null||contact.snapshot().down||replayName))release('scroll');scrollProgress();},{passive:true});
on(canvas,'keydown',e=>{if(!renderer||progress>.45)return;if(e.key==='Escape'){release('escape');return;}if((e.key==='Enter'||e.key===' ')&&!e.repeat){active='keyboard';begin([.42,.55],e,'keyboard');}},{passive:true});
on(canvas,'keyup',e=>{if(active==='keyboard'&&(e.key==='Enter'||e.key===' '))release('keyboard up',true);},{passive:true});on(canvas,'blur',()=>{if(active==='keyboard')release('focus left');});
on(document,'visibilitychange',()=>{if(document.hidden){pointers.clear();gestureBlocked=false;release('hidden');stopRAF('hidden');}else{lastTime=0;requestDraw();}});
const observer=new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;if(!inView){release('offscreen');stopRAF('offscreen');}else{lastTime=0;requestDraw();}},{threshold:0});observer.observe(stage);
const resizeObserver=new ResizeObserver(size);resizeObserver.observe(stage);on(window,'orientationchange',()=>{release('orientation');size();},{passive:true});
on(reduced,'change',()=>{grid?.reset();requestDraw();status.textContent=reduced.matches?'動きを低減。固定した面で奥の像が応じます。':'触れる・横に動かす / 縦に進む';});
on(canvas,'webglcontextlost',e=>{e.preventDefault();generation++;loader?.abort();release('context lost');stopRAF('context lost');renderer?.dispose();renderer=null;stage.dataset.renderer='static';status.textContent='描画が中断しました。静止画で縦進行できます。復旧時に面を再構成します。';});
on(canvas,'webglcontextrestored',()=>{stats.restoreCount++;ready();});
function setGrid(enabled){settings.grid=Boolean(enabled);$('#grid-toggle').checked=settings.grid;grid?.reset();draw();requestDraw();}
function setQuality(name){if(!['full','balanced'].includes(name))throw Error('Unknown quality');if(destroyed)return;settings.quality=name;$('#quality').value=name;size();ready();}
function reset(){release('reset');contact.reset();grid?.reset();pendingReaction=null;const previous=window.scrollY;stage.scrollIntoView({behavior:'instant',block:'start'});expectedScrollY=previous!==window.scrollY?window.scrollY:null;scrollProgress();draw();requestDraw();}
function replay(name='shorttap'){name=name==='shortTap'?'shorttap':name;if(!['shorttap','hold','drag'].includes(name))throw Error('Unknown replay');if(!renderer||!live())return false;release('replay start');reset();const hit=name==='drag'?[.32,.55]:[.42,.55];if(!begin(hit,null,'replay'))return false;replayName=name;replayStart=performance.now();later(()=>release('replay up',true),name==='shorttap'?120:name==='hold'?1200:900);return true;}
on($('#grid-toggle'),'change',e=>setGrid(e.target.checked));on($('#quality'),'change',e=>setQuality(e.target.value));on($('#replay'),'click',()=>replay($('#replay-select').value));on($('#reset'),'click',reset);on($('#overlay'),'input',e=>{$('#reference').style.opacity=Number(e.target.value)/100;});
function suspend(){suspended=true;generation++;loader?.abort();release('pagehide');stopRAF('pagehide');renderer?.dispose();renderer=null;grid?.dispose();grid=null;gridKey='';stage.dataset.renderer='static';pointers.clear();gestureBlocked=false;}
on(window,'pagehide',suspend);on(window,'pageshow',e=>{if(e.persisted&&!destroyed){suspended=false;contact.reset();size();if(!renderer)ready();}});
function destroy(){if(destroyed)return;suspend();destroyed=true;observer.disconnect();resizeObserver.disconnect();for(const remove of removers)remove();removers.length=0;canvas.width=1;canvas.height=1;status.textContent='描画資源と入力を解放しました。静止画を表示中。';}
function sampled(uv){if(!frame)return null;const base=surfacePoint(uv,[.42,.55],0,frame),p=pose(),delta=p.grid&&grid&&(p.contact>0||grid.active)?grid.sample(uv):[0,0,0];return base.map((v,i)=>v+delta[i]);}
function snapshot(){const c=contact.snapshot();return{state:{...c,active,target:c.target,amount:c.contact,transition,progress,passiveReveal,reduced:reduced.matches,grid:settings.grid,quality:settings.quality,lastRelease:stats.lastRelease,replay:replayName},pose:pose(),settings:{...settings},frame:frame?{...frame}:null,renderer:stage.dataset.renderer,canvas:[canvas.width,canvas.height],mesh:renderer?.mesh||null,plate:renderer?.plate||null,grid:grid?{...grid.diagnostics(),active:grid.active,revision:grid.revision}:null,stats:{...stats,frameIntervals:[...stats.frameIntervals],solverTimes:[...stats.solverTimes],drawingTimes:[...stats.drawingTimes],samples:[...stats.samples],inputs:[...stats.inputs],reactions:[...stats.reactions],rafLog:[...stats.rafLog]},raf,destroyed,suspended,inView,generation,timers:timers.size,pointers:[...pointers]};}
window.discoveryPreview={snapshot,state:()=>snapshot().state,stats:()=>snapshot().stats,sample:sampled,setGrid,setQuality,replay,reset,destroy,release:()=>release('diagnostic cancel'),loseContext:()=>renderer?.gl.getExtension('WEBGL_lose_context'),hitFromEvent:e=>hitFromEvent(e),ridgeTrace:(count=101)=>Array.from({length:count},(_,i)=>{const y=(i/(count-1)-.5)*frame.scaleY+.5,uv=[ridgeAt(y,frame.controls),y],p=sampled(uv);return{uv,screen:[p[0],(p[1]-.5)/frame.scaleY+.5],z:p[2]};})};
$('#grid-toggle').checked=settings.grid;$('#quality').value=settings.quality;size();
