import {vertexSource,fragmentSource} from './material.js';
export async function createRenderer(canvas,device,quality='full',{signal}={}){
 const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,depth:false,preserveDrawingBuffer:true,powerPreference:'low-power'});if(!gl)throw Error('WebGL2 unavailable');
 const buffers=[],textures=[],shaders=[];let program,vao,disposed=false,image=null;
 const dispose=()=>{if(disposed)return;disposed=true;buffers.forEach(b=>gl.deleteBuffer(b));textures.forEach(t=>gl.deleteTexture(t));shaders.forEach(s=>gl.deleteShader(s));if(program)gl.deleteProgram(program);if(vao)gl.deleteVertexArray(vao);signal?.removeEventListener('abort',abort);};
 const abort=()=>{if(image)image.src='';dispose();};signal?.addEventListener('abort',abort,{once:true});
 const check=()=>{if(disposed||signal?.aborted)throw new DOMException('Renderer load cancelled','AbortError');};
 try{
 check();const shader=(type,src)=>{const s=gl.createShader(type);if(!s)throw Error('Shader allocation failed');shaders.push(s);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'Shader compilation failed');return s;};program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertexSource));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragmentSource));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'Shader link failed');
 const nx=quality==='balanced'?192:256,ny=quality==='balanced'?144:192,verts=new Float32Array((nx+1)*(ny+1)*2),indices=new Uint16Array(nx*ny*6);let k=0;for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){verts[k++]=x/nx;verts[k++]=y/ny;}k=0;for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const i=y*(nx+1)+x;indices.set([i,i+1,i+nx+1,i+1,i+nx+2,i+nx+1],k);k+=6;}vao=gl.createVertexArray();gl.bindVertexArray(vao);for(const [target,data]of[[gl.ARRAY_BUFFER,verts],[gl.ELEMENT_ARRAY_BUFFER,indices]]){const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(target,b);gl.bufferData(target,data,gl.STATIC_DRAW);}const a=gl.getAttribLocation(program,'aUv');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);
 const texture=unit=>{const t=gl.createTexture();textures.push(t);gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t;};
 const gridTex=texture(0);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,1,1,0,gl.RGBA,gl.FLOAT,new Float32Array(4));
 const plateTex=texture(1);image=new Image();image.src=`assets/s1-${device}.webp`;await image.decode();check();const plate={width:image.naturalWidth,height:image.naturalHeight,path:new URL(image.src,location.href).href,device,cover:'center',textures:1};gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,plateTex);gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL,gl.NONE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,gl.RGBA,gl.UNSIGNED_BYTE,image);image=null;
 const names=['Ridge','RidgeEnd','Aspect','ScaleY','Smooth','Amount','Grid','GridTex','GridSize','Plate','PlateSize','Resolution','Hit','Reveal','Transition','Debug'],u=Object.fromEntries(names.map(n=>[n,gl.getUniformLocation(program,'u'+n)]));let gridIdentity=null,gridRevision=-1;
 function draw(frame,pose,grid){if(disposed||gl.isContextLost())return false;gl.useProgram(program);gl.bindVertexArray(vao);gl.viewport(0,0,canvas.width,canvas.height);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,gridTex);gl.uniform1i(u.GridTex,0);const gridVisible=Boolean(pose.grid&&grid&&(pose.contact>0||grid.active));gl.uniform1f(u.Grid,gridVisible?1:0);
 if(gridVisible){gl.uniform2f(u.GridSize,grid.nx+1,grid.ny+1);if(gridIdentity!==grid){gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,grid.nx+1,grid.ny+1,0,gl.RGBA,gl.FLOAT,grid.data);gridIdentity=grid;gridRevision=grid.revision;}else if(gridRevision!==grid.revision){gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,grid.nx+1,grid.ny+1,gl.RGBA,gl.FLOAT,grid.data);gridRevision=grid.revision;}}
 gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,plateTex);gl.uniform1i(u.Plate,1);gl.uniform2f(u.PlateSize,plate.width,plate.height);gl.uniform2f(u.Resolution,canvas.width,canvas.height);gl.uniform4fv(u.Ridge,frame.controls.slice(0,4).map(c=>c[1]));gl.uniform1f(u.RidgeEnd,frame.controls[4][1]);gl.uniform1f(u.Aspect,frame.aspect);gl.uniform1f(u.ScaleY,frame.scaleY);gl.uniform1f(u.Amount,pose.contact);gl.uniform1f(u.Smooth,1);gl.uniform2fv(u.Hit,pose.hit);gl.uniform1f(u.Reveal,pose.reveal);gl.uniform1f(u.Transition,pose.transition);gl.uniform1f(u.Debug,pose.debug||0);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);return true;}
 return{draw,dispose,gl,plate,mesh:{nx,ny,vertices:verts.length/2,triangles:indices.length/3},get disposed(){return disposed;}};
 }catch(error){dispose();throw error;}
}
