const $=id=>document.getElementById(id);let results;const n=(v,d=3)=>Number.isFinite(v)?v.toFixed(d):'未計測';
function table(rows,head){return `<div class="table-wrap"><table><thead><tr><th scope="col">${head}</th><th scope="col">旧Smooth</th><th scope="col">Grid</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r[0]}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`;}
function render(){const d=$('device').value,phase=$('phase').value;for(const p of ['smooth','grid']){const stem=`evidence/${d}-${p}`,file=`${stem}-${phase}.png`;$(`${p}-image`).src=file;$(`${p}-link`).href=file;const v=$(`${p}-video`);v.pause();v.src=`${stem}.mp4`;v.poster=`${stem}-before.png`;$(`${p}-download`).href=`${stem}.mp4`;$(`${p}-download`).download=`awai-${d}-${p}.mp4`;}
 $('other-hits').innerHTML=[[.2,.3],[.75,.65],[.55,.5]].map((hit,i)=>`<h3>面UV (${hit.join(', ')})</h3><div class="pair">${['smooth','grid'].map(p=>`<figure><figcaption>${p==='grid'?'Grid':'旧Smooth'}</figcaption><a href="evidence/${d}-${p}-hit${i+1}.png"><img loading="lazy" src="evidence/${d}-${p}-hit${i+1}.png" alt="${p} 接触位置${hit.join(', ')}"></a></figure>`).join('')}</div>`).join('');
 if(!results)return;const pair=['smooth','grid'].map(p=>results.metrics[`${d}-${p}`]),row=(label,fn)=>[label,...pair.map(fn)];
 $('metrics').innerHTML=table([row('横 最大移動',m=>`${n(m.ridge.dxPx.max,2)} px / 幅${n(m.ridge.maxPercentW,3)}%`),row('縦 最大移動',m=>`${n(m.ridge.dyPx.max,2)} px / 高さ${n(m.ridge.maxPercentH,3)}%`),row('合成移動 最大 / RMS',m=>`${n(m.ridge.movementPx.max,2)} / ${n(m.ridge.movementPx.rms,2)} px`),row('面積比 最小 / 平均',m=>`${n(m.mesh.jacobian.min)} / ${n(m.mesh.jacobian.mean)}`),row('最小線方向比 最小 / 平均',m=>`${n(m.mesh.singularMin.min)} / ${n(m.mesh.singularMin.mean)}`),row('全稜線曲率 最大 / RMS',m=>`${n(m.ridge.curvature.max,2)} / ${n(m.ridge.curvature.rms,2)}`),row('追加沈みHessian RMS',m=>n(m.addedSagHessian.rms)),row('投影面反転',m=>m.mesh.negative),row('3D最大辺長の伸縮違反',m=>m.grid?`${n(m.grid.maxStrain*100,2)}%`:'拘束を解いていない')],d==='sp'?'スマホ':'PC');
 const perf=['smooth','grid'].map(p=>results.performance[`${d}-${p}`]);$('performance').innerHTML=table([['荷重解除から自然復帰',...perf.map(p=>`${n(p.recoveryMs/1000,2)} 秒`)],['解除中 solver CPU / callback',...perf.map(p=>p.releaseMeanSolverCpuMs==null?'格子計算なし':`${n(p.releaseMeanSolverCpuMs,2)} ms`)],['最大 solver CPU / callback',...perf.map(p=>p.maxSolverCpuMs?`${n(p.maxSolverCpuMs,2)} ms`:'格子計算なし')]],'収録したPC上の測定');
}
$('device').addEventListener('change',render);$('phase').addEventListener('change',render);$('play-both').addEventListener('click',async()=>{const vs=[$('smooth-video'),$('grid-video')];vs.forEach(v=>{v.pause();v.currentTime=0;});const r=await Promise.allSettled(vs.map(v=>v.play()));$('play-status').textContent=r.every(v=>v.status==='fulfilled')?'同じ接触位置・荷重で再生中。復元時間は各モデルの結果です。':'同時再生に制限があります。各動画の再生ボタンをご利用ください。';});
render();fetch('evidence/grid-results.json').then(r=>r.json()).then(r=>{results=r;render();$('test-summary').textContent=`PC／スマホ寸法のEdge自動検査 ${r.summary.pass}/${r.summary.pass+r.summary.fail} 合格。スマホ実機は未検証。`;}).catch(()=>{$('test-summary').textContent='検証結果JSONから確認してください。';$('metrics').textContent='計測結果を読み込めませんでした。';});
